import { describe, it, expect } from "vitest";
import { generateKeyPairSync, sign as ed25519Sign, createHash } from "node:crypto";
import {
  createExchange,
  jcsBytes,
  type AgentSigner,
  type IssuerSigner,
  type DataIntegrityProof,
  type UaidExchange,
} from "../src/index.js";
import {
  decodeMultibase,
  encodeMultibase,
  publicKeyFromVerificationMethod,
  verifyDataIntegrityProof,
  verifyChallengeProof,
  verifyExchange,
  UnsupportedVerificationMethodError,
} from "../src/verify.js";

// ---------------------------------------------------------------------------
// Test helper: a real Ed25519 keypair wired up as an AgentSigner/IssuerSigner
// with a did:key verificationMethod (multicodec 0xed 0x01 + raw key,
// multibase 'z'). No existing test in this package builds real keys (both
// uaid-exch.test.ts's mockSigner() and revocation.test.ts use no crypto at
// all — grepped, confirmed) so this helper is new, per the ticket's
// instruction to reuse existing patterns where they exist and build one
// where they don't.
// ---------------------------------------------------------------------------

function makeEd25519KeyPair() {
  const { publicKey, privateKey } = generateKeyPairSync("ed25519");
  const spkiDer = publicKey.export({ type: "spki", format: "der" });
  const rawPublicKey = new Uint8Array(spkiDer.subarray(spkiDer.length - 32));
  const multicodec = new Uint8Array([0xed, 0x01, ...rawPublicKey]);
  const mb = encodeMultibase(multicodec, "z");
  const verificationMethod = `did:key:${mb}#${mb}`;
  return {
    rawPublicKey,
    verificationMethod,
    async sign(bytes: Uint8Array): Promise<string> {
      const sig = ed25519Sign(null, bytes, privateKey);
      return encodeMultibase(new Uint8Array(sig), "z");
    },
  };
}

function agentSigner(agentUuaid: string): AgentSigner & { rawPublicKey: Uint8Array } {
  const kp = makeEd25519KeyPair();
  return { agentUuaid, verificationMethod: kp.verificationMethod, sign: kp.sign, rawPublicKey: kp.rawPublicKey };
}

function issuerSigner(issuerDid: string): IssuerSigner & { rawPublicKey: Uint8Array } {
  const kp = makeEd25519KeyPair();
  return { issuerDid, verificationMethod: kp.verificationMethod, sign: kp.sign, rawPublicKey: kp.rawPublicKey };
}

function fingerprint(raw: Uint8Array): string {
  return createHash("sha256").update(raw).digest("hex");
}

async function buildExchange(agent: AgentSigner, issuer: IssuerSigner): Promise<UaidExchange> {
  return createExchange(
    {
      signingCredentialId: "uuaid:foundation:signing-credential:018f7ac8",
      principal: "did:web:acme.com",
      action: "sign.contract",
      counterparty: "did:web:customer.com",
      resource: { type: "application/pdf", sha256: "sha256:abc123", size: 184321 },
      purpose: "MSA Q3 renewal",
      soleControl: {
        challenge_type: "webauthn-prf",
        challenge_at: "2026-07-04T18:12:31.804Z",
        challenge_evidence_hash: "sha256:def456",
      },
      now: () => new Date("2026-07-04T18:12:33.412Z"),
      idFactory: () => "018f7ad5-4d3d-7ac8-8e11-4e6c9e2c6b3a",
    },
    agent,
    issuer
  );
}

// ---------------------------------------------------------------------------
// decodeMultibase / encodeMultibase
// ---------------------------------------------------------------------------

describe("decodeMultibase / encodeMultibase", () => {
  it("round-trips base58btc ('z') including leading zero bytes", () => {
    const bytes = new Uint8Array([0, 0, 1, 2, 3, 255, 254]);
    const mb = encodeMultibase(bytes, "z");
    expect(mb[0]).toBe("z");
    expect(decodeMultibase(mb)).toEqual(bytes);
  });

  it("round-trips base64url ('u') without padding", () => {
    const bytes = new Uint8Array(32).fill(9);
    const mb = encodeMultibase(bytes, "u");
    expect(mb[0]).toBe("u");
    expect(mb).not.toContain("=");
    expect(decodeMultibase(mb)).toEqual(bytes);
  });

  it("rejects an unsupported multibase prefix", () => {
    expect(() => decodeMultibase("Zabc")).toThrow(/unsupported multibase prefix/);
  });

  it("rejects an empty string", () => {
    expect(() => decodeMultibase("")).toThrow();
  });

  it("rejects an invalid base58btc character (e.g. '0', excluded from the alphabet)", () => {
    expect(() => decodeMultibase("z0")).toThrow(/invalid base58btc character/);
  });
});

// ---------------------------------------------------------------------------
// publicKeyFromVerificationMethod
// ---------------------------------------------------------------------------

describe("publicKeyFromVerificationMethod", () => {
  it("decodes a did:key generated by this test's own signer (multicodec 0xed 0x01 + 32 bytes) back to the exact raw key", () => {
    const kp = makeEd25519KeyPair();
    expect(publicKeyFromVerificationMethod(kp.verificationMethod)).toEqual(kp.rawPublicKey);
  });

  it(
    "did:key W3C spec vector — decode/re-encode self-consistency only. " +
      "This test does NOT assert the raw key bytes for " +
      "did:key:z6MkhaXgBZDvotDkL5257faiztiGiC2QtKLGpbnnEGta2doK against an " +
      "independently-cited source: the ticket allowed falling back to a " +
      "self-generated round-trip when the raw bytes cannot be cited with " +
      "confidence, and that is the path taken here (see the previous test " +
      "for the full generate→encode→decode→match round trip). This test " +
      "only checks that decoding the published identifier succeeds, yields " +
      "the expected shape (34 bytes total: the 2-byte Ed25519 multicodec " +
      "prefix 0xed 0x01 + 32 key bytes), and that re-encoding those bytes " +
      "reproduces the original string.",
    () => {
      const did = "did:key:z6MkhaXgBZDvotDkL5257faiztiGiC2QtKLGpbnnEGta2doK";
      const mb = did.slice("did:key:".length);
      const decoded = decodeMultibase(mb);
      expect(decoded.length).toBe(34);
      expect(decoded[0]).toBe(0xed);
      expect(decoded[1]).toBe(0x01);
      expect(encodeMultibase(decoded, "z")).toBe(mb);
      // And the high-level accessor agrees this is a well-formed, usable key.
      expect(() => publicKeyFromVerificationMethod(did)).not.toThrow();
      expect(publicKeyFromVerificationMethod(did).length).toBe(32);
    }
  );

  it("accepts a raw Ed25519 JWK ({kty:'OKP', crv:'Ed25519', x})", () => {
    const kp = makeEd25519KeyPair();
    const x = encodeMultibase(kp.rawPublicKey, "u").slice(1); // strip the 'u' multibase prefix -> bare base64url
    const jwk = { kty: "OKP", crv: "Ed25519", x };
    expect(publicKeyFromVerificationMethod(jwk)).toEqual(kp.rawPublicKey);
  });

  it("rejects a JWK with the wrong crv", () => {
    const kp = makeEd25519KeyPair();
    const x = encodeMultibase(kp.rawPublicKey, "u").slice(1);
    expect(() =>
      publicKeyFromVerificationMethod({ kty: "OKP", crv: "P-256", x })
    ).toThrow(UnsupportedVerificationMethodError);
  });

  it("rejects a JWK whose x decodes to the wrong length", () => {
    expect(() =>
      publicKeyFromVerificationMethod({ kty: "OKP", crv: "Ed25519", x: "AQID" })
    ).toThrow(/expected 32-byte "x", got 3/);
  });

  it("rejects a did:key with the wrong multicodec prefix", () => {
    const wrongPrefix = new Uint8Array([0x00, 0x00, ...new Uint8Array(32)]);
    const did = `did:key:${encodeMultibase(wrongPrefix, "z")}`;
    expect(() => publicKeyFromVerificationMethod(did)).toThrow(
      UnsupportedVerificationMethodError
    );
    expect(() => publicKeyFromVerificationMethod(did)).toThrow(/multicodec prefix/);
  });

  it("rejects a JWK carrying extra key material (G6: e.g. a private 'd') even when kty/crv/x are otherwise valid", () => {
    const kp = makeEd25519KeyPair();
    const x = encodeMultibase(kp.rawPublicKey, "u").slice(1);
    expect(() =>
      publicKeyFromVerificationMethod({ kty: "OKP", crv: "Ed25519", x, d: "shouldNotBeHere" } as unknown as JsonWebKey)
    ).toThrow(UnsupportedVerificationMethodError);
    expect(() =>
      publicKeyFromVerificationMethod({ kty: "OKP", crv: "Ed25519", x, d: "shouldNotBeHere" } as unknown as JsonWebKey)
    ).toThrow(/extra field/);
    // An unrelated extra field is rejected the same way — the allowlist is
    // exact, not just "must not carry 'd'".
    expect(() =>
      publicKeyFromVerificationMethod({ kty: "OKP", crv: "Ed25519", x, kid: "key-1" } as unknown as JsonWebKey)
    ).toThrow(/extra field/);
  });

  it("rejects a verificationMethod that is neither did:key nor a recognized JWK — does not invent an 'ed25519:<hex>' form", () => {
    // Confirmed by grep across src/ and tests/: no "ed25519:" verification
    // method form exists anywhere in this package, so it is intentionally
    // unsupported here rather than invented.
    expect(() => publicKeyFromVerificationMethod("ed25519:" + "ab".repeat(32))).toThrow(
      UnsupportedVerificationMethodError
    );
    expect(() => publicKeyFromVerificationMethod("uuaid:foundation:agent:018f#sk-1")).toThrow(
      UnsupportedVerificationMethodError
    );
    expect(() => publicKeyFromVerificationMethod({} as never)).toThrow(
      UnsupportedVerificationMethodError
    );
  });
});

// ---------------------------------------------------------------------------
// verifyDataIntegrityProof / verifyChallengeProof
// ---------------------------------------------------------------------------

describe("verifyDataIntegrityProof", () => {
  it("signs jcsBytes(document) directly (createExchange's construction) — a proof computed the W3C double-hash way over the same document+key is rejected", async () => {
    const kp = makeEd25519KeyPair();
    const document = { hello: "world", n: 1 };
    const proofShape = {
      type: "DataIntegrityProof" as const,
      cryptosuite: "eddsa-jcs-2022" as const,
      created: "2026-07-04T18:12:33.412Z",
      verificationMethod: kp.verificationMethod,
      proofPurpose: "authentication" as const,
    };

    // createExchange's actual construction (index.ts:229-234): sign
    // jcsBytes(document) directly — no proof-options hash at all.
    const realProof: DataIntegrityProof = {
      ...proofShape,
      proofValue: await kp.sign(jcsBytes(document)),
    };
    expect(verifyDataIntegrityProof(document, realProof).ok).toBe(true);

    // The W3C eddsa-jcs-2022 cryptosuite's construction instead:
    // sha256(JCS(proofConfig)) || sha256(JCS(document)), proofConfig being
    // the proof options (this same shape) without proofValue.
    const w3cBytes = new Uint8Array([
      ...createHash("sha256").update(jcsBytes(proofShape)).digest(),
      ...createHash("sha256").update(jcsBytes(document)).digest(),
    ]);
    const w3cProof: DataIntegrityProof = { ...proofShape, proofValue: await kp.sign(w3cBytes) };

    // This module mirrors createExchange's simpler construction, not the
    // W3C one — a proof computed the W3C way, over the identical document
    // and key, is rejected as a bad signature.
    const w3cResult = verifyDataIntegrityProof(document, w3cProof);
    expect(w3cResult.ok).toBe(false);
    expect(w3cResult.reason).toBe("signature verification failed");
  });

  it("rejects an unsupported proof type", async () => {
    const kp = makeEd25519KeyPair();
    const document = { a: 1 };
    const proof = {
      type: "Ed25519Signature2020",
      cryptosuite: "eddsa-jcs-2022",
      created: "2026-07-04T18:12:33.412Z",
      verificationMethod: kp.verificationMethod,
      proofPurpose: "authentication",
      proofValue: await kp.sign(jcsBytes(document)),
    } as unknown as DataIntegrityProof;
    const result = verifyDataIntegrityProof(document, proof);
    expect(result.ok).toBe(false);
    expect(result.reason).toMatch(/unsupported proof type/);
  });

  it("rejects an unsupported cryptosuite", async () => {
    const kp = makeEd25519KeyPair();
    const document = { a: 1 };
    const proof: DataIntegrityProof = {
      type: "DataIntegrityProof",
      cryptosuite: "eddsa-2022" as unknown as "eddsa-jcs-2022",
      created: "2026-07-04T18:12:33.412Z",
      verificationMethod: kp.verificationMethod,
      proofPurpose: "authentication",
      proofValue: await kp.sign(jcsBytes(document)),
    };
    const result = verifyDataIntegrityProof(document, proof);
    expect(result.ok).toBe(false);
    expect(result.reason).toMatch(/unsupported cryptosuite/);
  });

  it("rejects the wrong proofPurpose when one is expected", async () => {
    const kp = makeEd25519KeyPair();
    const document = { a: 1 };
    const proof: DataIntegrityProof = {
      type: "DataIntegrityProof",
      cryptosuite: "eddsa-jcs-2022",
      created: "2026-07-04T18:12:33.412Z",
      verificationMethod: kp.verificationMethod,
      proofPurpose: "authentication",
      proofValue: await kp.sign(jcsBytes(document)),
    };
    const result = verifyDataIntegrityProof(document, proof, {
      expectedProofPurpose: "assertionMethod",
    });
    expect(result.ok).toBe(false);
    expect(result.reason).toMatch(/proofPurpose mismatch/);
  });

  it("rejects a bad multibase proofValue", async () => {
    const kp = makeEd25519KeyPair();
    const document = { a: 1 };
    const proof: DataIntegrityProof = {
      type: "DataIntegrityProof",
      cryptosuite: "eddsa-jcs-2022",
      created: "2026-07-04T18:12:33.412Z",
      verificationMethod: kp.verificationMethod,
      proofPurpose: "authentication",
      proofValue: "not-a-multibase-value!",
    };
    const result = verifyDataIntegrityProof(document, proof);
    expect(result.ok).toBe(false);
    expect(result.reason).toMatch(/bad multibase proofValue/);
  });

  it("rejects an explicitly-passed public key of the wrong length", async () => {
    const kp = makeEd25519KeyPair();
    const document = { a: 1 };
    const proof: DataIntegrityProof = {
      type: "DataIntegrityProof",
      cryptosuite: "eddsa-jcs-2022",
      created: "2026-07-04T18:12:33.412Z",
      verificationMethod: kp.verificationMethod,
      proofPurpose: "authentication",
      proofValue: await kp.sign(jcsBytes(document)),
    };
    const result = verifyDataIntegrityProof(document, proof, { publicKey: new Uint8Array(16) });
    expect(result.ok).toBe(false);
    expect(result.reason).toMatch(/invalid public key length/);
  });

  it("rejects a tampered document (signature no longer matches)", async () => {
    const kp = makeEd25519KeyPair();
    const document = { a: 1 };
    const proof: DataIntegrityProof = {
      type: "DataIntegrityProof",
      cryptosuite: "eddsa-jcs-2022",
      created: "2026-07-04T18:12:33.412Z",
      verificationMethod: kp.verificationMethod,
      proofPurpose: "authentication",
      proofValue: await kp.sign(jcsBytes(document)),
    };
    const result = verifyDataIntegrityProof({ a: 2 }, proof);
    expect(result.ok).toBe(false);
    expect(result.reason).toBe("signature verification failed");
  });

  it("verifyChallengeProof round-trips a plain object with no embedded proof field", async () => {
    const kp = makeEd25519KeyPair();
    const challenge = {
      type: "esig-signer-challenge/v1",
      envelopeId: "018f7000",
      signerId: "signer-1",
      htmlSha256: "sha256:aaa",
      nonce: encodeMultibase(new Uint8Array(32).fill(7), "u"),
      issuedAt: "2026-08-27T00:00:00.000Z",
      expiresAt: "2026-08-27T00:15:00.000Z",
    };
    const proof: DataIntegrityProof = {
      type: "DataIntegrityProof",
      cryptosuite: "eddsa-jcs-2022",
      created: "2026-08-27T00:00:00.000Z",
      verificationMethod: kp.verificationMethod,
      proofPurpose: "authentication",
      proofValue: await kp.sign(jcsBytes(challenge)),
    };
    const ok = verifyChallengeProof(challenge, proof);
    expect(ok.ok).toBe(true);
    expect(ok.keyFingerprint).toBe(fingerprint(kp.rawPublicKey));

    const tampered = { ...challenge, nonce: encodeMultibase(new Uint8Array(32).fill(8), "u") };
    expect(verifyChallengeProof(tampered, proof).ok).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// verifyExchange — the full createExchange() round trip
// ---------------------------------------------------------------------------

describe("verifyExchange", () => {
  it("verifies a genuine createExchange() output end to end, keys resolved from did:key verificationMethods", async () => {
    const agent = agentSigner("uuaid:foundation:agent:018f7abc");
    const issuer = issuerSigner("uuaid:foundation:certifier:018f7aaa");
    const exchange = await buildExchange(agent, issuer);

    const result = verifyExchange(exchange);
    expect(result.ok).toBe(true);
    expect(result.failures).toEqual([]);
    expect(result.agent.ok).toBe(true);
    expect(result.agent.keyFingerprint).toBe(fingerprint(agent.rawPublicKey));
    expect(result.issuer.ok).toBe(true);
    expect(result.issuer.keyFingerprint).toBe(fingerprint(issuer.rawPublicKey));
  });

  it("rejects an exchange whose body was tampered with after signing — both proofs fail", async () => {
    const agent = agentSigner("uuaid:foundation:agent:018f7abc");
    const issuer = issuerSigner("uuaid:foundation:certifier:018f7aaa");
    const exchange = await buildExchange(agent, issuer);

    const tampered: UaidExchange = {
      ...exchange,
      credentialSubject: {
        ...exchange.credentialSubject,
        exchange: { ...exchange.credentialSubject.exchange, purpose: "something else entirely" },
      },
    };

    const result = verifyExchange(tampered);
    expect(result.ok).toBe(false);
    expect(result.agent.ok).toBe(false);
    expect(result.issuer.ok).toBe(false);
    expect(result.failures).toHaveLength(2);
  });

  it("rejects when the wrong public key is supplied for a slot", async () => {
    const agent = agentSigner("uuaid:foundation:agent:018f7abc");
    const issuer = issuerSigner("uuaid:foundation:certifier:018f7aaa");
    const exchange = await buildExchange(agent, issuer);
    const wrongKey = agentSigner("someone-else").rawPublicKey;

    const result = verifyExchange(exchange, { agentPublicKey: wrongKey });
    expect(result.ok).toBe(false);
    expect(result.agent.ok).toBe(false);
    expect(result.issuer.ok).toBe(true); // issuer slot untouched
  });

  it("rejects when the two proofs are swapped (proofPurpose no longer matches its slot)", async () => {
    const agent = agentSigner("uuaid:foundation:agent:018f7abc");
    const issuer = issuerSigner("uuaid:foundation:certifier:018f7aaa");
    const exchange = await buildExchange(agent, issuer);
    const swapped: UaidExchange = { ...exchange, proof: [exchange.proof[1], exchange.proof[0]] };

    const result = verifyExchange(swapped);
    expect(result.ok).toBe(false);
    expect(result.agent.reason).toMatch(/proofPurpose mismatch/);
    expect(result.issuer.reason).toMatch(/proofPurpose mismatch/);
  });

  it("rejects a proof array that isn't exactly length 2", async () => {
    const agent = agentSigner("uuaid:foundation:agent:018f7abc");
    const issuer = issuerSigner("uuaid:foundation:certifier:018f7aaa");
    const exchange = await buildExchange(agent, issuer);
    const malformed: UaidExchange = { ...exchange, proof: [exchange.proof[0]] };

    const result = verifyExchange(malformed);
    expect(result.ok).toBe(false);
    expect(result.failures[0]).toMatch(/expected exactly 2 proofs/);
  });

  it("rejects an exchange whose issuer proof uses an unsupported cryptosuite", async () => {
    const agent = agentSigner("uuaid:foundation:agent:018f7abc");
    const issuer = issuerSigner("uuaid:foundation:certifier:018f7aaa");
    const exchange = await buildExchange(agent, issuer);
    const withBadCryptosuite: UaidExchange = {
      ...exchange,
      proof: [
        exchange.proof[0],
        { ...exchange.proof[1], cryptosuite: "eddsa-2022" as unknown as "eddsa-jcs-2022" },
      ],
    };

    const result = verifyExchange(withBadCryptosuite);
    expect(result.ok).toBe(false);
    expect(result.agent.ok).toBe(true);
    expect(result.issuer.reason).toMatch(/unsupported cryptosuite/);
  });
});
